# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

TEMPLATE = app
QT += core gui widgets
CONFIG += console
INCLUDEPATH +=.
DEPENDPATH +=.
include(Graphics_Programming-Project1.pri)
